version: "3.9"

services:
  postgres:
    image: postgres:14.6-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bauamt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.jmix/postgres:/var/lib/postgresql/data
